distro: bionic
branches:
  only:
  - test
sudo: required
language:
- bash
services:
- docker
env:
- OKD_VERSION="3.11.0" # OpenShift Origin (OKD)
before_install:
  - wget https://github.com/openshift/origin/releases/download/v3.11.0/openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit.tar.gz -O /tmp/oc.tar.gz
  - mkdir /tmp/ocdir && cd /tmp/ocdir && tar -xvf /tmp/oc.tar.gz
  - sudo mv  /tmp/ocdir/*/oc /tmp/ocdir/*/kubectl  /usr/local/bin/
script:
  - docker version
  - oc version
  - |
   cat << EOF | sudo tee /etc/docker/daemon.json
   {
       "insecure-registries" : [ "172.30.0.0/16" ]
   }
   EOF
  - sudo systemctl restart docker
  - oc cluster up
  # - curl http://127.0.0.1:8443 #OKD Cluster listening on local interface
  # - curl https://127.0.0.1:8443/console #Access Admin Console in a browser
after_install:
  - oc status
