# OpenShift Deployment
# https://docs.travis-ci.com/user/deployment-v2/providers/openshift/
language: java
jdk:
  - openjdk11
deploy:
  provider: openshift
  server:
  token:
  project:
  # user: test
